cantidad_notas = int(input("Ingrese la cantidad de notas: "))
contador_nota = int(1)
notas_aprobadas = int(0)
notas_desaprobada = int(0)
prom_notas_aprobadas = int(0)
prom_notas_desaprobadas = int(0)
prom_total_notas = int(0)
while (contador_nota <= cantidad_notas):
    valor_nota = int(input(f"Ingrese la nota numero {contador_nota}:  "))
    if (valor_nota < 70):
        notas_desaprobada = int(notas_desaprobada + 1)
        prom_notas_desaprobadas = int(prom_notas_desaprobadas + valor_nota)
    else: notas_aprobadas = int(notas_aprobadas + 1); prom_notas_aprobadas = int(prom_notas_aprobadas + valor_nota)
    prom_total_notas = int(prom_total_notas + (valor_nota/cantidad_notas))
    contador_nota = int(contador_nota + 1)
prom_notas_desaprobadas = int(prom_notas_desaprobadas / notas_desaprobada)
prom_notas_aprobadas = int(prom_notas_aprobadas / notas_aprobadas)
print(f"La cantidad de notas aprobadas del estudiante son {notas_aprobadas}")
print(f"Ël promedio de las notas aprobadas es {prom_notas_aprobadas}")
print(f"La cantidad de notas desaprobadas del estudiante son {notas_desaprobada}")
print(f"El promedio de las notas desaprobadas es {prom_notas_desaprobadas}")
print(f"El promedio total de notas es {prom_total_notas}")